name: First Workflow

on:
    push

jobs: 
    read-file_jobs:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Repo
          uses: actions/checkout@v6
          
        - name: Welcome Message
          run: echo "This is my 1st workflow on GitHub Actions"

        - name: Read File
          run: cat "README.md"

        - name: List Files
          run: ls -ltra
