name: First_WorkFlow

on: push

jobs:
    sample:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v6
        - name: List Files
          run: ls -ltra
        - name: Read File
          run: cat README.md

          
        - name: Sleep 15s
          run: sleep 15s
