name: Matrix Configuration

on: 
    workflow_dispatch: 

jobs:
    multi-os:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
            image: [hello-world, alpine]
        runs-on: ${{ matrix.os }}
        steps:
        - name: docker details
          run: docker info

        - name: docker run on ${{matrix.os}}
          run: docker run ${{matrix.image}}

