name: Multiple Jobs

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay CMD
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "I'm a DRAGON...ROAR...!!!" >> dragon.txt

        - name: Upload dragon.txt
          uses: actions/upload-artifact@v7
          with:
            name: my-artifact
            path: dragon.txt

    test:
        needs: build

        concurrency: 
            group: testing
            cancel-in-progress: false

        runs-on: ubuntu-latest
        steps:
        - name: Download dragon.txt
          uses: actions/download-artifact@v7
          with:
            name: my-artifact
            
        - name: Check dragon.txt
          run: grep -i dragon "dragon.txt"

        - name: Sleep for 65s     
        #   timeout-minutes: 1   
          run: sleep 65s

          
    deploy:
        needs: test
        runs-on: ubuntu-latest

        steps:

        - name: Download dragon.txt
          uses: actions/download-artifact@v7
          with:
            name: my-artifact

        - name: Read dragon.txt file
          run: cat dragon.txt