name: Multi Jobs

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay CMD
          run: sudo apt-get install -y cowsay

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "I'm a DRAGON...ROAR..." >> dragon.txt

        - name: Upload Dragon File
          uses: actions/upload-artifact@v7
          with:
            name: dragon-text-file
            path: dragon.txt

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon File
          uses: actions/download-artifact@v7
          with:
            name: dragon-text-file

        - name: Test Dragon FIle
          run: grep -i "dragon" dragon.txt

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon File
          timeout-minutes: 1
          uses: actions/download-artifact@v7
          with:
            name: dragon-text-file

        - name: Read Dragon File
          run: cat dragon.txt

        - name: List Files
          run: ls

        - name: Sleep 65s
          run: sleep 65s